# common vars
availability_zone: melbourne-qh2-uom

#volume
volumes:
  - vol_name: vol-1
    vol_size: 65
  - vol_name: vol-2
    vol_size: 65
  - vol_name: vol-3
    vol_size: 60
  - vol_name: vol-4
    vol_size: 60

#security group
security_groups:
  - name: demo_ssh
    description: "security group for ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "security group for main couchdb access"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 60000
    remote_ip_prefix: 0.0.0.0/0
  - name: docker_swarm
    description: "security group for swarm access"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "security group for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#instances
instance_name: server
instance_image: 394a1b97-a8d3-4593-aab0-8156f0dfeeca
instance_key_name: test
instance_flavor: uom.general.4c16g
instance_network: qh2-uom
